name: release-dockerhub

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Convert repository name to lowercase
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build, tag and push Docker image
        run: |
          IMG="${DOCKER_USERNAME}/${REPO_LC}"
          echo "${IMG}"
          docker build --tag $IMG:latest .
          docker push --all-tags $IMG