name: release

on:
  push:
  workflow_dispatch:

env:
  VERSION: "-1.0.0"

jobs:

  # starts flask application and gets version
  get-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Flask Application
      run: |
        python src/main.py &

    - name: Get Version
      id: get-version
      run: |
        RESPONSE=$(curl -s http://localhost:8080/v)
        VERSION=$(echo "$RESPONSE" | jq -r '.version')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Stop Flask Application
      run: |
        pkill -f "python src/main.py"

  # builds docker image and releases it to ghcr
  release:
    runs-on : ubuntu-latest
    needs: get-version
    steps:
      - uses: actions/checkout@v3

      - name: Print version
        run: |
          echo "Version: $VERSION"

      - name: Convert repository name to lowercase
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
      
      - name: Registry Login (ghcr.io)
        run: |
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMG=ghcr.io/michracz00/$REPO_LC
          docker build --tag $IMG:latest .
          docker push --all-tags $IMG